-- CMS V2: owner-authored public About page. This is intentionally a fixed,
-- structured document rather than free-form HTML or a generic page builder.
CREATE TABLE IF NOT EXISTS cms_about_pages (
  page_id TEXT PRIMARY KEY CHECK (page_id = 'about'),
  hero_eyebrow TEXT NOT NULL DEFAULT '' CHECK (length(hero_eyebrow) <= 160),
  hero_heading TEXT NOT NULL CHECK (length(hero_heading) BETWEEN 1 AND 160),
  hero_intro TEXT NOT NULL DEFAULT '' CHECK (length(hero_intro) <= 4000),
  hero_media_id TEXT REFERENCES cms_media_assets(id) ON DELETE RESTRICT,
  hero_alt_text TEXT NOT NULL DEFAULT '' CHECK (length(hero_alt_text) <= 500),
  why_eyebrow TEXT NOT NULL DEFAULT '' CHECK (length(why_eyebrow) <= 160),
  why_heading TEXT NOT NULL DEFAULT '' CHECK (length(why_heading) <= 160),
  why_body TEXT NOT NULL DEFAULT '' CHECK (length(why_body) <= 6000),
  why_media_id TEXT REFERENCES cms_media_assets(id) ON DELETE RESTRICT,
  why_alt_text TEXT NOT NULL DEFAULT '' CHECK (length(why_alt_text) <= 500),
  approach_eyebrow TEXT NOT NULL DEFAULT '' CHECK (length(approach_eyebrow) <= 160),
  approach_heading TEXT NOT NULL DEFAULT '' CHECK (length(approach_heading) <= 160),
  approach_body TEXT NOT NULL DEFAULT '' CHECK (length(approach_body) <= 6000),
  approach_media_id TEXT REFERENCES cms_media_assets(id) ON DELETE RESTRICT,
  approach_alt_text TEXT NOT NULL DEFAULT '' CHECK (length(approach_alt_text) <= 500),
  story_eyebrow TEXT NOT NULL DEFAULT '' CHECK (length(story_eyebrow) <= 160),
  story_heading TEXT NOT NULL DEFAULT '' CHECK (length(story_heading) <= 160),
  story_body TEXT NOT NULL DEFAULT '' CHECK (length(story_body) <= 6000),
  story_media_id TEXT REFERENCES cms_media_assets(id) ON DELETE RESTRICT,
  story_alt_text TEXT NOT NULL DEFAULT '' CHECK (length(story_alt_text) <= 500),
  future_eyebrow TEXT NOT NULL DEFAULT '' CHECK (length(future_eyebrow) <= 160),
  future_heading TEXT NOT NULL DEFAULT '' CHECK (length(future_heading) <= 160),
  future_body TEXT NOT NULL DEFAULT '' CHECK (length(future_body) <= 6000),
  future_media_id TEXT REFERENCES cms_media_assets(id) ON DELETE RESTRICT,
  future_alt_text TEXT NOT NULL DEFAULT '' CHECK (length(future_alt_text) <= 500),
  cta_eyebrow TEXT NOT NULL DEFAULT '' CHECK (length(cta_eyebrow) <= 160),
  cta_heading TEXT NOT NULL DEFAULT '' CHECK (length(cta_heading) <= 160),
  cta_body TEXT NOT NULL DEFAULT '' CHECK (length(cta_body) <= 4000),
  primary_cta_label TEXT NOT NULL DEFAULT '' CHECK (length(primary_cta_label) <= 120),
  primary_cta_destination TEXT NOT NULL DEFAULT '' CHECK (length(primary_cta_destination) <= 512),
  secondary_cta_label TEXT NOT NULL DEFAULT '' CHECK (length(secondary_cta_label) <= 120),
  secondary_cta_destination TEXT NOT NULL DEFAULT '' CHECK (length(secondary_cta_destination) <= 512),
  visibility TEXT NOT NULL DEFAULT 'visible' CHECK (visibility IN ('visible', 'hidden')),
  publication_state TEXT NOT NULL DEFAULT 'published' CHECK (publication_state IN ('published')),
  published_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  published_by TEXT NOT NULL CHECK (length(published_by) BETWEEN 1 AND 255),
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by TEXT NOT NULL CHECK (length(updated_by) BETWEEN 1 AND 255),
  CHECK (hero_media_id IS NULL OR length(hero_alt_text) BETWEEN 1 AND 500),
  CHECK (why_media_id IS NULL OR length(why_alt_text) BETWEEN 1 AND 500),
  CHECK (approach_media_id IS NULL OR length(approach_alt_text) BETWEEN 1 AND 500),
  CHECK (story_media_id IS NULL OR length(story_alt_text) BETWEEN 1 AND 500),
  CHECK (future_media_id IS NULL OR length(future_alt_text) BETWEEN 1 AND 500)
);

CREATE INDEX IF NOT EXISTS idx_cms_about_pages_public
ON cms_about_pages (page_id, publication_state, visibility);
